# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ASUS/Desktop/Vivado video series/Tutorial_1/Tutorial_1.srcs/sources_1/bd/VGA_source_bd/ip/VGA_source_bd_clk_wiz_0/VGA_source_bd_clk_wiz_0.xci
# IP: The module: 'VGA_source_bd_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ASUS/Desktop/Vivado video series/Tutorial_1/Tutorial_1.srcs/sources_1/bd/VGA_source_bd/ip/VGA_source_bd_clk_wiz_0/VGA_source_bd_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_source_bd_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/ASUS/Desktop/Vivado video series/Tutorial_1/Tutorial_1.srcs/sources_1/bd/VGA_source_bd/ip/VGA_source_bd_clk_wiz_0/VGA_source_bd_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_source_bd_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/ASUS/Desktop/Vivado video series/Tutorial_1/Tutorial_1.srcs/sources_1/bd/VGA_source_bd/ip/VGA_source_bd_clk_wiz_0/VGA_source_bd_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_source_bd_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/ASUS/Desktop/Vivado video series/Tutorial_1/Tutorial_1.srcs/sources_1/bd/VGA_source_bd/ip/VGA_source_bd_clk_wiz_0/VGA_source_bd_clk_wiz_0.xci
# IP: The module: 'VGA_source_bd_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ASUS/Desktop/Vivado video series/Tutorial_1/Tutorial_1.srcs/sources_1/bd/VGA_source_bd/ip/VGA_source_bd_clk_wiz_0/VGA_source_bd_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_source_bd_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/ASUS/Desktop/Vivado video series/Tutorial_1/Tutorial_1.srcs/sources_1/bd/VGA_source_bd/ip/VGA_source_bd_clk_wiz_0/VGA_source_bd_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_source_bd_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/ASUS/Desktop/Vivado video series/Tutorial_1/Tutorial_1.srcs/sources_1/bd/VGA_source_bd/ip/VGA_source_bd_clk_wiz_0/VGA_source_bd_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_source_bd_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
