# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ASUS/Desktop/Vivado video series/Tutorial_1/Tutorial_1.srcs/sources_1/bd/VGA_source_bd/ip/VGA_source_bd_VGA_SOURCE_0_0/VGA_source_bd_VGA_SOURCE_0_0.xci
# IP: The module: 'VGA_source_bd_VGA_SOURCE_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/ASUS/Desktop/Vivado video series/Tutorial_1/Tutorial_1.srcs/sources_1/bd/VGA_source_bd/ip/VGA_source_bd_VGA_SOURCE_0_0/ip/v_tc_0/v_tc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v_tc_0 || ORIG_REF_NAME==v_tc_0} -quiet] -quiet

# XDC: c:/Users/ASUS/Desktop/Vivado video series/Tutorial_1/Tutorial_1.srcs/sources_1/bd/VGA_source_bd/ip/VGA_source_bd_VGA_SOURCE_0_0/ip/v_tc_0/v_tc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v_tc_0 || ORIG_REF_NAME==v_tc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: c:/Users/ASUS/Desktop/Vivado video series/Tutorial_1/Tutorial_1.srcs/sources_1/bd/VGA_source_bd/ip/VGA_source_bd_VGA_SOURCE_0_0/VGA_source_bd_VGA_SOURCE_0_0.xci
# IP: The module: 'VGA_source_bd_VGA_SOURCE_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/ASUS/Desktop/Vivado video series/Tutorial_1/Tutorial_1.srcs/sources_1/bd/VGA_source_bd/ip/VGA_source_bd_VGA_SOURCE_0_0/ip/v_tc_0/v_tc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v_tc_0 || ORIG_REF_NAME==v_tc_0} -quiet] -quiet

# XDC: c:/Users/ASUS/Desktop/Vivado video series/Tutorial_1/Tutorial_1.srcs/sources_1/bd/VGA_source_bd/ip/VGA_source_bd_VGA_SOURCE_0_0/ip/v_tc_0/v_tc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v_tc_0 || ORIG_REF_NAME==v_tc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
