# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constr/constr.xdc

# Block Designs: bd/VGA_source_bd/VGA_source_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_source_bd || ORIG_REF_NAME==VGA_source_bd} -quiet] -quiet

# IP: bd/VGA_source_bd/ip/VGA_source_bd_VGA_SOURCE_0_0/VGA_source_bd_VGA_SOURCE_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_source_bd_VGA_SOURCE_0_0 || ORIG_REF_NAME==VGA_source_bd_VGA_SOURCE_0_0} -quiet] -quiet

# IP: bd/VGA_source_bd/ip/VGA_source_bd_clk_wiz_0/VGA_source_bd_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_source_bd_clk_wiz_0 || ORIG_REF_NAME==VGA_source_bd_clk_wiz_0} -quiet] -quiet

# XDC: bd/VGA_source_bd/VGA_source_bd_ooc.xdc
